import React from 'react'
import Header from '../components/header/Header'

const TermsandConditions = () => {
    return (
        <div>
            <Header />
            <div className='container'>
                <div className='row'>
                    <div className='d-flex align-items-center mt-3'>
                        <div className='breadcrum-box'>
                            <span>Home</span>
                        </div>
                        <span className='breadcrum-color'>Terms and Conditions
                        </span>
                    </div>
                    <div className='country-head text-center'>
                        <h2 className='mt-3'>
                            Terms and Conditions


                        </h2>
                        <p>We have some rules and set processes for utmost customer satisfaction.</p>
                    </div>
                    <div>
                        <p>Welcome to the Design Print Banner LLC (DPB LLC) website, operating under the domain bannerbuzz.com. The following Terms of Service (TOS) contain the terms and conditions that govern your use of the website bannerbuzz.com. Use of the DPB LLC website constitutes acceptance of these TOS. Bannerbuzz.com is a trademark of DPB LLC.</p>
                        <p>These TOS constitute the entire and only agreement between DPB LLC and you (User), and supersedes all prior or contemporaneous agreements, representations, warranties, and understandings. These TOS apply to all users who use DPB LLC. Users in this context shall include end users whether registered or not on DPB LLC.</p>
                        <p>DPB LLC reserves the right to add, delete, and/or modify any of the terms and conditions contained in these TOS, at any time and in its sole discretion, by posting a change notice or a new agreement on the DPB LLC website. If User deems any modifications as unacceptable, User’s only recourse is to not use the website bannerbuzz.com and its services. User’s continued use of DPB LLC’s bannerbuzz.com website will constitute binding acceptance of the changes.</p>
                        <p>DPB LLC uses other affiliated companies or third parties to provide certain products and services accessible through the website. DPB LLC does not control those third parties or their services. Users agree that DPB LLC will not be liable to you in any way for your use of such services as our affiliates or third parties may have their own Terms and Conditions. In case of conflicts between affiliate and DPB LLC Terms and Conditions, you must comply with DPB LLC's TOS.</p>
                        <h5>Eligibility to use this website</h5>
                        <p>DPB LLC will knowingly provide service to customers that can lawfully enter into and form contracts under applicable law. If User is under the age of 18, but at least 13 years of age, he/she may use the DPB LLC services under supervision of parent or legal guardian after they agree to these TOS. The DPB LLC website is not intended for children under the age of 13.</p>
                        <p>DPB LLC’s website bannerbuzz.com grants Users limited revocable license to access and use the website for its offered services, subject to Users' compliance with these TOS. DPB LLC does not allow customers to collect information or use information collected on the website to compete with DPB LLC or to create derivative work based on the content of the website. If User uses the information other than as per the TOS, DPB LLC may revoke access and pursue other legal courses of action permitted under applicable state or federal law.</p>
                        <h5>Registration, Security and Communication</h5>
                        <p><strong>Registration:</strong></p>
                        <p>You may register on our site to create your DPB LLC account. By completing registration, you hereby clearly agree, acknowledge, and grant us to access your personal information available in your account as per our privacy policy. You shall not use this site for any other purpose other than as mentioned on the site or for products/services that are not allowed under applicable law in any manner.</p>
                        <p>You agree to provide true, accurate, and complete information while transacting or registering or for any other purpose when prompted to do so on the site. You are prohibited from misrepresenting your identity and agree not to represent yourself as another User or login/register using the identity of any other person. You are responsible for maintaining and promptly updating the information provided while registering or for any other purpose on the site to ensure that the information provided by you is true, accurate, current, and complete at all times. If you provide any information that is untrue, inaccurate, not current, or incomplete, or DPB LLC has reasonable grounds to deduce that such information is untrue, inaccurate, not current, incomplete, or not in accordance with this User Agreement, DPB LLC reserves the right to indefinitely suspend, terminate, or block your use or access to the site in any manner whatsoever.</p>
                        <p><strong>Security:</strong></p>
                        <p>You are solely responsible for maintaining secrecy and confidentiality of your login credentials. You hereby acknowledge and accept that the site will grant access to any person who has obtained your login credentials in the same manner as it would have granted access to you and that you are responsible for all activities conducted under your account. DPB LLC, its employees, or any and all of its associates shall never be responsible in any manner for any kind of losses whatsoever occurring from such breaches of security.</p>
                        <p><strong>Electronic Communication:</strong></p>
                        <p>You agree and acknowledge to keep yourself updated with all data, information, and communication pertaining to you including but not limited to correspondence email ID, mobile number, and other relevant details. You further agree that your use of the site or provision of any data or information including any correspondence (by email or otherwise) to or by DPB LLC is through electronic records and that you give consent to receive communication from DPB LLC via electronic records which will be deemed adequate service of notice/electronic record.<br /><br />By submitting this form, you agree to receive marketing text messages from us at the number provided, including messages sent by autodialer. Consent is not a condition of purchase. Message and data rates may apply. Message frequency may vary. View our Privacy Policy and Terms &amp; Conditions to know more.<br /><br />By using this Service, you consent to receive certain electronic communications from us . You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including communications in writing.</p>
                        <p><strong>License:</strong></p>
                        <p>Subject to the terms and conditions of this agreement, we grant to you a non-exclusive, non-transferable license to use DPB LLC. You shall use the Licensed Program, i.e. website, of DPB LLC for your own use only. You shall not, however, transfer or sublicense the same to any third party, in whole or in part, in any form, whether modified or unmodified.</p>
                        <p><strong>Technical requirements:</strong></p>
                        <p>You may only register and transact with DPB LLC if you have the necessary technical requirements at your disposal. You shall have an internet-connected PC or smart phone with at least a 3G internet connection. You clearly agree and acknowledge that ensuring the availability and proper functioning of these technical requirements is your sole responsibility.</p>
                        <p>The instructions (step-by-step procedures displayed on various forms) “How to Use” DPB LLC will be available on the homepage/relevant pages of the site. All Users are to ensure that they read and adhere to these instructions (steps) for accessing DPB LLC. The User agrees that DPB LLC shall not be held responsible in the event of any occurrence due to the non-adherence of these instructions which prevents the user from using the site as designed or due to any reasons over which DPB LLC have no control.</p>
                        <p><strong>Payment Policy:</strong></p>
                        <p>Payment shall be made as per the product price list available on DPB LLC subject to offers available on the site from time to time.</p>
                        <p>Further, the DPB LLC reserves the right to introduce new products/services or to modify/upgrade existing products/services provided on the site. Additionally, DPB LLC may, at its sole discretion, introduce new charges for the new or modified/upgraded products/services provided. Changes to the User Agreement or any of the rules and policies of DPB LLC shall be posted on the site, and such changes shall automatically become effective immediately after being posted on the site. Further, DPB LLC reserves the right to issue a warning or temporarily/indefinitely suspend or terminate your registration with the site and disallow access to the site.</p>
                        <p>Online Payments must be made using payment software of a payment gateway service provider in accordance with the terms and conditions, privacy policy, and other policies of the payment gateway. The user clearly agrees and acknowledges that DPB LLC shall not be held responsible in the event of any delays, errors, or frauds in processing of payment by entities outside the control of DPB LLC.</p>
                        <p>DPB LLC uses payment systems as authorized by the central bank of America. DPB LLC neither makes any representations nor makes any warranties regarding the amount of time needed to complete processing, including delays in the online payment system, and nor shall DPB LLC be liable for any actual or consequential damages arising from any claim of delay or any payment process-related errors or delays.</p>
                        <p><strong>Maintenance:</strong></p>
                        <p>Site access is not possible during maintenance periods. Users may be informed about maintenance periods wherever possible.</p>
                        <p>User agrees and acknowledges that DPB LLC shall never be held responsible for any problems and related damages that may arise due to internet malfunctions/connectivity issues and when the site is closed for maintenance/updating with or without prior notice.</p>
                        <h5>Prohibited Use:</h5>
                        <p>User can only use the website as expressly permitted by DPB LLC. User may not cause harm to the website. Specifically, but not by way of limitation, User may not:</p>
                        <ul className="fancyCheck">
                            <li>Interfere with website performance by using viruses or any other technology or program designed to affect performance, content, and/or appearance of the website.</li>
                            <li>Modify or create derivatives of work by reverse engineering, decompiling, or disassembling any technology.</li>
                            <li>Collect any user information used for registration.</li>
                        </ul>
                        <p><strong>User Obligations</strong></p>
                        <p>You agree and undertake not to host, display, upload, modify, publish, transmit, update, or share any information or list any information or item that:</p>
                        <ul className="fancyCheck">
                            <li>belongs to another person and to which you do not have any right to;</li>
                            <li>is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially/ethnically objectionable, disparaging, relating to or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever, or unlawfully threatening, unlawfully harassing or harming minors in any way;</li>
                            <li>infringes any patent, trademark, copyright, or other proprietary rights, third party’s trade secrets, rights of publicity, or privacy, or involves fraudulent transactions or the sale of counterfeit or stolen items;</li>
                            <li>violates any law for the time being in force;</li>
                            <li>deceives or misleads the addressee/users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                            <li>impersonates another person or uses an anonymous proxy;</li>
                            <li>contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, ransomware, cancelbots, Easter eggs, or other computer programming routines that may damage, detrimentally interfere with, diminish the value of, surreptitiously intercept, or expropriate any system, data, or personal information;</li>
                            <li>threatens the unity, integrity, defense, security, or sovereignty of America, friendly relations with foreign states or public order, or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation;</li>
                            <li>is false, inaccurate or misleading;</li>
                            <li>directly or indirectly offers, attempts to offer, trades, or attempts to trade in dealings which are prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation, or guideline for the time being in force;</li>
                            <li>may give rise to liability on part of the site or the DPB LLC or cause any hindrance (in whole or in part).</li>
                        </ul>
                        <p>In case of any violation of the above provisions, DPB LLC has the right to immediately terminate the access or usage rights of the User to the site without any notice, and any such violative information that is displayed or submitted on the site can be removed immediately and completely.</p>
                        <p>You shall be responsible for keeping backup versions of the information and data that belongs to you. You hereby agree that you will not expect the site to restore or keep back up of your information and data and not hold the site or DPB LLC accountable for any loss of data in any circumstances.</p>
                        <p>You will also refrain from accessing information or databases in an unauthorized manner from the site or servers where information or databases are kept.</p>
                        <p>You shall not attempt to circumvent or manipulate any of the obligations conferred on you by this User Agreement. If such attempt is discovered, it will constitute sufficient ground for termination of access to the site and for taking appropriate legal actions.</p>
                        <p>If you choose to provide feedback on the site which is visible to other users, you shall exercise due care while making comments and not make any comments that are not factual in nature and shall not post defamatory, illegal, or offensive/obscene content.</p>
                        <p>You undertake not to disclose or distribute any other User's information to a third party, or use the information for any unauthorized purpose including for the purposes of marketing unless you have obtained the User's express consent to do so.</p>
                        <p>You shall not place any advertisements on the site in any manner. Further, you shall not use the site to promote any other person’s business or interests on the site unless expressly permitted by DPB LLC in writing.</p>
                        <h5>Copyright</h5>
                        <p>All the content including but not limited to: designs, graphics, organizations, and digital conversions related to DPB LLC website are protected under applicable copyrights, trademarks, and other property rights. Copying, downloading, or redistribution of any such matters or any part of site, except outlined in these TOS, is strictly prohibited.</p>
                        <p>User will retain ownership of the content that is used, referred, or uploaded by User during the use of the site. While using any outside content, User grants following licenses to DPB LLC: the non-exclusive, worldwide, transferable, sublicensable right to copy, crop, reproduce, publicly display, sell, and distribute design in or on products and in advertising, marketing, samples, and promotional materials for DPB LLC, and the right to make modifications to Users' design.</p>
                        <p>User may remove the design, graphics, or file, designed or uploaded by the User, at any time during the usage of the website. After the content designed by the user is transferred to the DPB LLC, if User chooses to remove that content, please notify DPB LLC in writing. Any orders that have been derived from that content will be fulfilled prior to the written notification of termination.</p>
                        <p>If User believes that her/his work has been copied in a way that constitutes copyright infringement, please provide our copyright agent (sales@bannerbuzz.com) the following information:</p>
                        <ul className="fancyCheck">
                            <li>Written document with signature of the person authorized to act on behalf of the owner of the copyright interest.</li>
                            <li>Details on the material that is claimed as infringed.</li>
                            <li>Contract information.</li>
                            <li>Our Agent will quickly act on any such notice received.</li>
                        </ul>
                        <h5>Reservation of Rights:</h5>
                        <p>DPB LLC reserves the right but does not assume the obligation to monitor transactions and communication that occurs through the website. If DPB LLC determines, in its sole and absolute discretion, that User has breached a term or condition of these TOS, DPB LLC may cancel such transactions and restrict access.</p>
                        <p>DPB LLC may modify the site bannerbuzz.com at any time without any prior notice and will incur no liability for doing so.</p>
                        <h5>Representation and Warranties:</h5>
                        <p>User of the site represents and warrants to DPB LLC that in use of the bannerbuzz.com site, User will not infringe the copyright, trademark, patent, trade secret, right of privacy, right of publicity, or other legal right of any third party. User further represents and warrants to DPB LLC that there are no claims, demands, or any form of litigation pending to the best of User's knowledge, threatened with respect to any of User's content. DPB LLC will not be required to pay any third party related to using the content provided by the User. User’s content should not cause direct or indirect injury to any third party and should be free of viruses or any other program or technology that can cause direct or indirect damage to the site.</p>
                        <h5>Disclaimer and Exclusions:</h5>
                        <p>DPB LLC provides a website service (bannerbuzz.com) on an 'as is' and 'as available' basis. DPB LLC does not represent or warrant that site will be uninterrupted, will be free of errors and inaccuracies, will be reliable, will be timely, and will meet User's requirements. DPB LLC makes no warranties other than those made expressly in these TOS, and hereby disclaims any and all implied warranties, including without limitation, warranties of fitness for a particular purpose, merchantability, and non-infringement.</p>
                        <p>DPB LLC will not be liable to any User or any third party for any consequential, incidental, indirect, punitive, or special damages including damages relating to lost profits, lost data, or loss of goodwill arising out of, relating to, or connected with (a) the use of the site or any service or products based on any cause of action, even if advised of the possibility of such damages, (b) the content contained on the site, or (c) any delay or failure in performance beyond control of the Covered Party.</p>
                        <h5>Limitation of Liability:</h5>
                        <p>Limitation of liability, except for a breach of a party's representations and warranties under these TOS or in connection with your indemnity obligations under these TOS, in no event will the liability of DPB LLC exceed the value of the products ordered or serviced rendered. The value of the products or services are limited to the stated value on the DPB LLC site bannerbuzz.com or the amount charged to the customer.</p>
                        <h5>Indemnification:</h5>
                        <p>User must indemnify and hold DPB LLC and its employees, partners, suppliers, representatives, agents, affiliates, directors, officers, managers, and shareholders (if applicable) harmless from any damage, loss, or expenses (including without limitation reasonable attorney's fees and costs) incurred in connection with any third-party claim, demand, or action (“Claim”) brought against any of the parties alleging that User has breached any of these TOS through any act of omission, including but not limited to any claim that your content infringes or violates the rights of any other party. If you have to indemnify DPB LLC under this section, DPB LLC will have the right to control the defense, settlement, and resolution of any Claim and your sole expense. You may not settle or otherwise resolve any Claim without DPB LLC’s express written permission.</p>
                        <h5>Termination:</h5>
                        <p>These TOS will survive indefinitely unless and until DPB LLC terminates them. DPB LLC may suspend or terminate User’s use of the website bannerbuzz.com if it believes, in its sole and absolute discretion, that you have breached the terms of these TOS.</p>
                        <p>If either User or DBP LLC terminate User use of bannerbuzz.com, DPB LLC may delete any Content or other materials relating to your use of DPB website or services on the DPB servers or otherwise in its possession and DPB LLC will have no liability to you or any third party for doing so.</p>
                        <h5>Registration:</h5>
                        <p>By registering on our website, you will be automatically subscribed to our newsletter subscription / promotional emailer / SMS programs.</p>
                        <p>User might be asked to register at the site. User must agree to provide accurate, complete registration information. Each registration is for personal use only and access to that information should not be made available to any third party. DPB LLC does not permit any third party to view, alter, or in any way use User’s registration section.</p>
                        <h5>Color Matching:</h5>
                        <p>DPB LLC uses standard industry software for designing and printing purposes and sells products via a website accessed by internet-connected devices. There are differences in construction and configuration between computer screens and monitors. The fact that there is no true uniformity in standards to which monitors and screens must conform results in a variance in color from monitor to monitor, screen to screen. Further, monitors use light to display images and use a standard known as RGB. DPB LLC produces colors on a variety of machines, none of which use light. As such, User agrees that DPB LLC does not guarantee exact color matching or that printed colors will appear exactly as they do on User’s screen or monitor. Slight color variations are possible and will not be considered a production mistake and will not be eligible for refund or return or reproduction. DPB LLC uses best judgment to match colors, but if you need visually matching colors, we suggest ordering sample product.</p>
                        <h5>Production:</h5>
                        <p>DPB LLC uses production facilities inside and outside of the country. It cannot guarantee where the production will happen for each product and order. Your order may be manufactured in the United States or abroad.</p>
                        <h5>Design Proofing:</h5>
                        <p>DPB LLC will not proofread any design made by the User. Please double check all your designs before submitting the order. DPB LLC cannot be held responsible for mistakes in design made by the customer.</p>
                        <p>DPB LLC will print the file you submit as is. In the case where a proof is requested, DPB LLC will produce the last proof approved by the User. Any changes to the proof have to be done before approval of the proof.</p>
                        <h5>Materials</h5>
                        <p>Design Print Banner&nbsp;LLC sells products made out of several different types of materials:&nbsp;High Quality PVC Flex,&nbsp;PVC Mesh,&nbsp;Polyester Fabric,&nbsp;Processed Cloth (Plastic Satin material),&nbsp;PVC Free Flex, 100% Polyester Mesh Fabric, Art Cotton Canvas,&nbsp;Corflute, Reflective Film, aluminum, mesh fabric, etc.</p>
                        <p>You agree that you have read our website and/or researched independently and that you know what each of these materials is and what you are buying.&nbsp;Design Print Banner&nbsp;LLC only guarantees that you will receive the materials advertised on the Web Site that you purchase. You agree that&nbsp;Design Print Banner&nbsp;LLC is not responsible for products received that are made of materials thought by the purchaser to be something other than advertised on the Web Site.</p>
                        <p>As an example, you agree&nbsp;Design Print Banner&nbsp;LLC is not responsible if the&nbsp;Corflute + Reflective Film&nbsp;received by the purchaser is not what the purchaser envisioned&nbsp;Corflute + Reflective Film&nbsp;would be.</p>
                        <p>You agree that all products produced and sold by&nbsp;Design Print Banner&nbsp;LLC are for novelty purposes only.&nbsp;Design Print Banner&nbsp;LLC does not make any claims about the legal compliance or registration of signs, license plates, or any other products sold by&nbsp;Design Print Banner&nbsp;LLC or by a&nbsp;Design Print Banner&nbsp;LLC affiliate. You agree to check with any applicable legal authority for the standards, rules and regulations governing the types of signs, license plates, or other products permitted for your particular use.</p>
                        <h5>Delays:</h5>
                        <p>DBP LLC shows estimated delivery date for each order on bannerbuzz.com. These dates are indicative dates only and are based on production-ready orders and don’t include any public holidays or shipping delays. Any delay due to shipping has to be addressed directly with the shipping company.</p>
                        <p>Production time and shipping time is a general reference guide only, the actual delivery date is subject to daily production capability and couriers’ performance. If the order is urgent or required by a specific date, please notify us and we will take necessary steps to ensure the order is sent out within the specified timeframe. However, we have no control over 3rd party couriers’ performance, and we are not liable for delays arising from couriers’ shipping service.</p>
                        <h5>Refund and Returns:</h5>
                        <p>Design Print Banner LLC guarantees the products it sells are free from manufacturing defects and as such will be good for 120 days after the purchase of the product. If the product fails or breaks due to a manufacturing defect during that time, you agree to take a photograph of the failed or broken product and send the photograph or the original failed or broken product to Design Print Banner LLC. Upon receipt of the product or the photograph, BannerBuzz will send a replacement of the product, issue a store credit, or will issue a refund via the original payment method for the purchase value of the failed or broken product(s). Design Print Banner LLC credit can be used on the BannerBuzz website for any purchase.</p>
                        <p>Design Print Banner LLC does not guarantee or warrant that its products will work for any intended purpose or in any set of conditions. You agree that the determination of whether a products failure or breakage is due to a manufacturing defect is within the sole discretion of Design Print Banner LLC. You further agree to provide full and complete information regarding the circumstances of the failure or breakage, including but not limited to the use of the product, the conditions the product was in, and any other information useful to an informed determination by Design Print Banner LLC as to the cause of the failure or breakage.</p>
                        <p>DPB LLC will not allow any refunds unless there is error on the part of DPB LLC. Refund value will be less than or equal to the sold price of the product excluding shipping charges. All refunds have to be approved by DPB LLC Customer Service. Refunds are issued within 15 business days after their approval. DPB LLC will not be responsible for any charges by banks or third party including but not limited to fees or interest.</p>
                        <p>We guarantee the products we sell are free from manufacturing defects and are good for 120 days after the purchase of the product. If the product fails or breaks due to a manufacturing defect during that time, take a photograph of the failed or broken product and send it to us. BannerBuzz will send a replacement of the product, issue store credit, or issue a refund via the original payment method for the purchase value of the failed or broken product(s). Design Print Banner LLC credit can be applied to any purchase on the BannerBuzz website. Please note, if there is no activity for a continuous period of 90 days, the order will be automatically cancelled, and the order amount paid by any mode by the user will be transferred to the Stores Credit of the user account.</p>
                        <p><strong>Stores' Credit Usage Policy</strong><br /><strong>Store credit balances can be used on the entire range of products on our website. It shall be valid for a period of 180 days from the date of credit.</strong></p>
                        <h5>Safety Signs Disclaimer:</h5>
                        <p>User is solely responsible for (a) identifying the appropriate precautions, including signage materials, language, and designs necessary to comply with any applicable local, state, or federal laws or regulations, including ANSI and/or OSHA standards and (b) adequately warning invitees, employees, and the public of any hazards. In some cases a sign may not provide an adequate safety precaution. DPB LLC is not a safety expert and disclaims any and all liability that the template designs offered on DPB LLC website are sufficient to cover any specific hazard. DPB LLC does not have responsibility to notify customers about changes in the law after sale. Customer shall hold DPB LLC and its subsidiaries, employees, and any and all of its associates harmless from all claims, loss or expense (including attorneys’ fees) related to the purchase and use by customer for any signed purchased through DPB LLC and DPB LLC website bannerbuzz.com</p>
                        <h5>Miscellaneous:</h5>
                        <p>These TOS will be binding upon each party hereto and its successors and permitted assigns, and governed by and construed in accordance with the laws of the State of South Carolina without reference to conflict of law principles. These TOS will not be assignable or transferable by User without the prior written consent of DPB LLC. These TOS contain the entire understanding of the parties regarding its subject matter and supersedes all prior and contemporaneous agreements and understanding between the parties regarding its subject matter. User and DPB LLC are independent contractors, and no agency, partnership, joint venture, or employee-employer relationship is intended or created by these TOS.</p>
                        <h5>Notice:</h5>
                        <p>All notices required or permitted to be given under these TOS will be in writing and delivered to the other party by any of the following methods: (a) U.S mail or Courier (b) Electronic Mail. All notices to DPB LLC should be sent to nishant.shah@bannerbuzz.com and also a hard copy with signature and contact information should be sent to the company’s address.</p>
                        <h5>Dispute Resolution:</h5>
                        <p>In the rare event of a dispute, all disputes arising out of, relating to, or connected with these TOS or your use of any part of the bannerbuzz.com service will be exclusively resolved under confidential binding arbitration in accordance with the commercial arbitration rules of JAMS. Any such controversy or claim shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any claim or controversy of any other party. Judgment on arbitration award may be entered in to any court having jurisdiction thereof. DPB LLC may seek equitable relief, including, without limitation, injunctive relief and specific performance without the requirement of posting a bond or other security or proving damages are insufficient, from a court of competent jurisdiction.</p>
                        <p><strong>Consent</strong></p>
                        <p>The contracting parties of this agreement give their consent, which is not only free but also legal and voluntary in nature, for the purposes of entering into this contract in terms of this Agreement and related policies.</p>
                        <p><strong>Actions in Good Faith</strong></p>
                        <p>Under this agreement, the actions of both the parties shall be deemed as actions in good faith (bona fide) unless there is evidence to the contrary.</p>
                        <p><strong>Language</strong></p>
                        <ul className="fancyCheck">
                            <li>All notices given under this agreement shall be in English.</li>
                            <li>If there is any inconsistency between any document and any version of the same document, the English version shall be deemed as effective and authoritative.</li>
                        </ul>
                        <p><strong>Injunction</strong></p>
                        <p>You clearly agree that breach of this agreement might cause us irreparable injury, for which monetary damages would not provide adequate compensation, and that in addition to compensation and any other remedy, we shall be entitled to injunctive relief against such breach or threatened breach, without proving actual damage.</p>
                        <p><strong>Non-Poaching</strong></p>
                        <p>You clearly agree and acknowledge that while this Agreement is in force and for a period of Twenty-Four (24) months thereafter, you shall not directly or indirectly solicit or offer employment to any of the DPB LLC’s officers, employees, third party contractors and associates who have been involved in or associated with this Agreement without DPB LLC’s prior consent. You clearly understand and agree that Twenty-Four (24) months period is reasonable after considering training and grooming time as well as investments made by DPB LLC.</p>
                        <p><strong>In the Event of Merger, Sale etc.</strong></p>
                        <p>In the event that DPB LLC is acquired by or merged with a third-party entity, we reserve the right to transfer or assign the information we have collected from our users as part of such merger, acquisition, sale, or other change of control. In the unlikely event of our bankruptcy, insolvency, reorganization, receivership, or assignment for the benefit of creditors, or the application of laws or equitable principles affecting creditors' rights generally, we may not be able to control how your personal information is treated, transferred, or used. Please direct any questions that you may have at any time to&nbsp;<a href="mailto:sales@bannerbuzz.com">sales@bannerbuzz.com</a></p>
                        <p><strong>Taxes</strong></p>
                        <p>You agree and acknowledge that we shall never be held responsible for any tax liabilities for your transactions. Further, for avoidance of doubt and notwithstanding anything to the contrary herein, You will indemnify, reimburse, and hold us harmless from, for, and against any sales, use, gross receipts, excise, franchise, business, or other taxes or fees (including penalties, fines, or interest thereon) imposed by any government or other taxing authority to the extent such taxes or fees are assessed on us which is your primary legal obligation.</p>
                        <p><strong>Waiver</strong></p>
                        <p>No failure or delay by DPB LLC in exercising any remedy, right, or privilege under or in relation to this Agreement shall operate as a waiver of the same, nor shall any single or partial exercise of any remedy, right, power, or privilege preclude any further exercise of any other right, power, or privilege.</p>
                        <p><strong>Heading</strong></p>
                        <p>The Clause headings in this Agreement are inserted for convenience only and shall not affect the interpretation of this Agreement.</p>
                        <p><strong>Force majeure</strong></p>
                        <p>DPB LLC shall be under no liability for any failure, delay, or omission by it in the performance of its obligations under this Agreement if such failure, delay, or omission arises from any cause beyond our control, including, but not limited to acts of god, acts or regulations of any governmental or supra-national authority, war or national emergency, fire, civil disobedience, strikes, lock-outs, technical black-outs like power failures, internet failures etc. and industrial disputes.</p>
                        <p><strong>Survival</strong></p>
                        <p>Unless and to the extent otherwise specified herein, all terms of this Agreement which by their nature extend beyond its termination including but not limited to privacy, payment, IPR, indemnity, restrictions, limited liability, arbitration, taxes, and others will remain in effect until fulfilled and apply to respective successors and assigns.</p>
                        <p><strong>Severability</strong></p>
                        <p>If any clause of this User Agreement or the application thereof to any user or circumstance shall be deemed invalid, void, or for any reason unenforceable to any extent, the remainder of this User Agreement and the application of such unenforceable provision to Users or circumstances other than those as to which it is held invalid or unenforceable shall not be affected thereby, and each provision of this User Agreement shall be valid and enforceable to the fullest extent permitted by law.</p>
                        <p><strong>Contract Interpretations</strong></p>
                        <p>In this agreement unless otherwise specified:</p>
                        <ul className="fancyCheck">
                            <li>Reference to a Subsidiary or Holding company is to be interpreted in accordance with the Corporate Laws;</li>
                            <li>Reference to a party is reference to a party of this agreement and this includes the party’s permitted assignees and/or the respective successors in title to the whole undertaking;</li>
                            <li>Reference to a person includes any person, individual, company, firm, corporation, government, state or agency of a state, or any undertaking regardless of it having a legal representative or not and notwithstanding of the law under which it exists;</li>
                            <li>Reference to any statute or statutory instrument or any of its provisions shall be interpreted as a statute or statutory instrument or provisions that is re-enacted or amended from time-to-time;</li>
                            <li>All words/terms denoting the singular shall include the plural and vice versa;</li>
                            <li>All words/terms denoting any gender shall include all genders;</li>
                            <li>All references to the clauses and Schedules shall be interpreted as reference to clauses or Schedules of this agreement.</li>
                        </ul>
                        <h5>BannerBuzz Wallet</h5>
                        <p>Please read the following terms and conditions (“T&amp;Cs”) carefully before registering for, accessing or using the BB Wallet (as defined below), located at <a href="https://www.bannerbuzz.com/">www.bannerbuzz.com</a> or any similar platform (hereinafter referred to as BannerBuzz Platform) on any device and/or before availing any e-wallet services.</p>
                        <p><strong>General Conditions for Wallet</strong></p>
                        <ul className="fancyCheck">
                            <li>You will be issued a Bannerbuzz Wallet Account only after successful registration.</li>
                            <li>You may not be able to add money or recharge your BannerBuzz wallet (or BB Wallet) through any payment method/s. Except as provided hereunder, any amount in your BannerBuzz Wallet will not be refunded to you under any circumstances.</li>
                            <li>You may note that withdrawing money from BBWallet is not allowed. Any outstanding credit or BB Points in the BannerBuzz Wallet must be utilized only to make payments for bona fide Transactions.</li>
                            <li>BannerBuzz Wallets are available only to users who have attained the age of 18 years and are competent to contract.</li>
                            <li>Bannerbuzz Wallets and its amount are not transferable.</li>
                            <li>BannerBuzz and/or Design Print Banner LLC (DPB LLC) reserves the right to suspend/discontinue BB Wallet services to you at any time, for any cause, including, but not limited, to the following-</li>
                            <li>The value stored on your BannerBuzz Wallet shall NOT be refunded under ANY circumstances and may only utilized to make payments for bona fide Transactions. No interest will be payable by BannerBuzz or Design Print Banner LLC (DPB LLC) on the available balance reflected on the BB Wallet</li>
                            <li>You are permitted to maintain and operate only one BannerBuzz wallet per user. Any suspected non-conformity with this requirement shall constitute grounds for the suspension/discontinuation by Design Print Banner LLC (DPB LLC) of any of all BannerBuzz Wallets associated with you on the BannerBuzz Platform. Any operation of or continued availability of any facility with respect to the BannerBuzz Wallets from time to time shall be subject to any requirements under applicable laws, and any new regulations or directions from any regulatory authorities in India.</li>
                        </ul>
                        <h5>Amendment of Terms, BannerBuzz Platform</h5>
                        <p>Design Print Banner LLC (DPB LLC) may modify, terminate and/or suspend BannerBuzz Wallet to the Customer anytime with or without prior notice, due to any changes in internal policies, rules, regulations and laws set by relevant authorities/regulators. Design Print Banner LLC (DPB LLC) reserves the right to change, modify, add, or remove portions of these T&amp;Cs (each, a change and collectively, changes) at any time or without prior notice, due to any changes in internal policies, rules, regulations and laws set by relevant authorities/regulators. If you do not agree with any such change, your sole and exclusive remedy is to terminate your use of the BannerBuzz Platform/BannerBuzz Wallet. Your continued use of the BannerBuzz Platform and the BB Wallet following the posting of changes will mean that you accept and agree to the changes.</p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default TermsandConditions